#!/bin/bash
# generated by make_experiment_matrix.py -- run from repo root
set -e
DATA=${DATA:-/p/lustre1/laubach2/nequip_models/quests_descriptors-Mar2026/DS_2km6t3p8hxx2_0.xyz}   # override: DATA=/path/on/this/machine.xyz bash $0
python pruning/make_masks.py $DATA results/fps/global_s0 results/pruned/global_s0 --fractions 0.050 0.100 0.200 --drop-descriptors
python pruning/make_masks.py $DATA results/fps/global_s1 results/pruned/global_s1 --fractions 0.050 0.100 0.200 --drop-descriptors
python pruning/make_masks.py $DATA results/fps/random_global_s0 results/pruned/random_global_s0 --fractions 0.050 0.100 0.200 --drop-descriptors
python pruning/make_masks.py $DATA results/fps/random_stratified_s0 results/pruned/random_stratified_s0 --fractions 0.050 0.100 0.200 --drop-descriptors
python pruning/make_masks.py $DATA results/fps/stratified_s0 results/pruned/stratified_s0 --fractions 0.050 0.100 0.200 --drop-descriptors
python pruning/make_masks.py $DATA results/fps/stratified_s1 results/pruned/stratified_s1 --fractions 0.050 0.100 0.200 --drop-descriptors
